### ISSUE TITLE
Stops to work

### ISSUE THREAD

**Issue by slavkoja** [bmrzycki/stunip#2]
I do not use it often, but from time to time i need to know my external IP, but recently it stops to work with default server. It is not consistent, sometime i got answer, but in most cases no. As it have not any verbose/debug option, i only see the 1 as return code.

The `tcpdump` shows 10 attempts:
```
22:59:00.219573 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:00.545471 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:00.546483 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:00.872440 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:00.873461 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:01.197579 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:01.198557 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:01.522809 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:01.524106 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:01.850272 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:01.851356 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:02.176980 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:02.178181 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:02.504053 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:02.505116 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:02.830855 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:02.831875 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:03.158051 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
22:59:03.159110 IP 192.168.10.1.39881 > 74.125.200.127.19305: UDP, length 20
22:59:03.485696 IP 74.125.200.127.19305 > 192.168.10.1.39881: UDP, length 32
```
But using `stunclient` works with any of the default STUN servers, here is the first:
```
stunclient stun.l.google.com 19305
Binding test: success
Local address: 192.168.10.1:42198
Mapped address: IP.AD.DR.ES:42198
```
Its `tcpdump` shows only one attempt:
```
23:08:22.360081 IP 192.168.10.1.39379 > 64.233.167.127.19305: UDP, length 28
23:08:22.397436 IP 64.233.167.127.19305 > 192.168.10.1.39379: UDP, length 32
```
As you can see, the `stunclient` sends 28 B, while `stunip` only 20 B. Perhaps something changed on google side?

**Comment by bmrzycki** [comment]
Hello @slavkoja , thank you for the report. I also discovered this yesterday after reviewing my server logs.

The reason `stunclient` sends 28 Bytes is likely due to it adhering to a newer RFC format while `stunip` uses the older RFC 3489 layout.

After debugging it looks like some of the default Google servers are responding using RFC 5389 even though I explicitly request RFC 3489. I verified the code never sends a transaction ID with the "magic cookie" which enables RFC 5389 mode. Even so, some of the Google replies contain the newer `XOR-MAPPED-ADDRESS` attribute. I've updated `stunip` with this fix, please try running using f0b4ead5b or newer and let me know if it fixes the issue for you.

**Comment by slavkoja** [comment]
seems to work ;-)

**Comment by bmrzycki** [comment]
Thanks for testing @slavkoja . I'll push a new tag and close this issue.
